1. Импортируйте пакет numpy под именем np

In [8]:
import numpy as np

2. Распечатайте версию numpy

In [9]:
print(np.__version__)

1.26.4


3. Создайте вектор со значениями от 10 до 49 

In [5]:
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [15]:
arr = (np.arange(10, 50))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [27]:
A = np.random.random((5,5))
print(A)

[[0.5354342  0.22064297 0.52672615 0.18962422 0.10780638]
 [0.56941592 0.19223182 0.43940486 0.33221195 0.84903373]
 [0.69514164 0.19410367 0.02530416 0.6925614  0.88133751]
 [0.84040575 0.61729961 0.11399288 0.51648402 0.97277065]
 [0.37692264 0.59039302 0.04489023 0.84697959 0.35232634]]


array([0.77621004, 0.63715337, 0.49428744, 0.81732248, 0.43085952])

In [31]:
np.average(A)

0.4689378123104941

In [32]:
np.median(A)

0.5164840228710524

6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [34]:
a = np.array([x for x in range(27)])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [36]:
print(a.reshape(3,3,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [37]:
a = np.array([[3.5, 1.9, 8.45], , [4.7, 7.9, 1.9]])

[[3 1 8]
 [4 7 1]]


In [45]:
a.astype(int)

array([[3, 1, 8],
       [4, 7, 1]])

8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [46]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

In [47]:
a.astype(bool)

array([[ True, False, False],
       [ True,  True,  True],
       [False, False,  True]])

9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [71]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [73]:
new_arr = (a1, a2)

In [77]:
print(np.hstack(new_arr))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [80]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


In [81]:
new_arr = (a1, a2)

In [82]:
np.vstack(new_arr)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [10, 11]])

11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

(array([0, 3, 4], dtype=int64),)


In [87]:
checker = (a, b)

In [88]:
np.where(checker)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [7]:
c = np.where(a == b)
c

(array([0, 3, 4], dtype=int64),)

12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [89]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [91]:
print(np.dot(a, b))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу

In [92]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [93]:
angles = np.array([3.14, 3.14/2, 6.28])

[ 0.00159265  0.99999968 -0.0031853 ]


In [95]:
print(np.sin(angles))

[ 0.00159265  0.99999968 -0.0031853 ]


15. Отсортировать вектор

In [96]:
v = np.random.random(size=[10])
print(v)

[0.47233563 0.44837828 0.30333186 0.16080574 0.63762542 0.05685227
 0.21588359 0.60754782 0.87851406 0.12701966]


[0.13178341 0.14962622 0.26204075 0.30821184 0.34446024 0.45199466
 0.51581108 0.79408365 0.87313982 0.88810901]


In [97]:
print(np.sort(v))

[0.05685227 0.12701966 0.16080574 0.21588359 0.30333186 0.44837828
 0.47233563 0.60754782 0.63762542 0.87851406]


16. Проверить, одинаковы ли два NumPy массива

In [109]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

True


In [99]:
print(a == b)

[ True  True  True  True  True]


In [102]:
print(np.equal(a, b))

[ True  True  True  True  True]


In [110]:
np.all(a == b)

True

17. В одномерном массиве заменить максимальный элемент на ноль

In [111]:
Z = np.random.random(10)

In [112]:
Z

array([0.32955365, 0.64361336, 0.53490249, 0.76139433, 0.60446288,
       0.41358759, 0.14858156, 0.5763634 , 0.92767219, 0.59623446])

[0.16782157 0.13655578 0.59454878 0.02957322 0.         0.71645444
 0.48757387 0.05812814 0.21499663 0.24011352]


In [115]:
maxind = np.argmax(Z)

In [116]:
Z[maxind] = 0

In [117]:
Z

array([0.32955365, 0.64361336, 0.53490249, 0.76139433, 0.60446288,
       0.41358759, 0.14858156, 0.5763634 , 0.        , 0.59623446])

18. Замените все нечетные числа одномерного массива на -1.

In [177]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
arr[arr % 2 != 0] = -1

In [180]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [158]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])

In [159]:
arr

array([ 0,  1, 20,  3,  4,  5,  6, -7,  8, 90])

In [160]:
arr[arr > 30] = 10

In [161]:
arr[arr < 5] = 10

In [162]:
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

20. Отсортируйте двумерный массив по столбцам

In [165]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])

In [182]:
print(a)

[[11  5  3]
 [ 4 15  6]
 [ 7  8 19]]


In [181]:
print(np.sort(a))

[[ 3  5 11]
 [ 4  6 15]
 [ 7  8 19]]
